# Generated by Django 5.1.4 on 2026-05-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='employee_id',
        ),
    ]
