# Generated by Django 5.1.4 on 2026-05-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0002_alter_activitylog_event_type'),
        ('FC', '0003_add_role_permissions'),
    ]

    operations = [
    ]
