# Generated by Django 6.0.5 on 2026-05-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0004_merge_20260512_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='faculty_type',
            field=models.CharField(blank=True, choices=[('all', 'All Faculty'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time')], default='all', help_text='Filter by faculty type when scope is college or department', max_length=20, null=True),
        ),
    ]
