# Generated by Django 5.1.4 on 2026-03-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0006_remove_activitylog_actor_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='admin_id',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='actor_admin_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
