# Generated by Django 5.1.4 on 2026-03-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0007_remove_activitylog_admin_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='requirement_id',
        ),
    ]
