# Generated by Django 5.1.4 on 2026-03-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0008_remove_activitylog_requirement_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='actor_admin_id',
        ),
    ]
