# Generated by Django 5.1.4 on 2026-03-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0009_remove_activitylog_actor_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='is_superadmin',
        ),
    ]
