# Generated by Django 5.1.4 on 2026-03-21 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0011_add_activitylog_admin_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clearance',
            new_name='FC_clearanc_academi_e5d704_idx',
            old_name='FC_clearanc_academi_7f9c77_idx',
        ),
        migrations.RenameIndex(
            model_name='clearance',
            new_name='FC_clearanc_faculty_28eaba_idx',
            old_name='FC_clearanc_faculty_f42c13_idx',
        ),
        migrations.RenameIndex(
            model_name='clearancerequest',
            new_name='FC_clearanc_clearan_a77ae5_idx',
            old_name='FC_clearanc_clearan_7dff0a_idx',
        ),
        migrations.RenameIndex(
            model_name='clearancerequest',
            new_name='FC_clearanc_status_2c2a92_idx',
            old_name='FC_clearanc_status_5c4b44_idx',
        ),
        migrations.RenameIndex(
            model_name='clearancetimeline',
            new_name='FC_clearanc_is_acti_9a9351_idx',
            old_name='FC_clearanc_is_acti_ae2d65_idx',
        ),
        migrations.RenameIndex(
            model_name='clearancetimeline',
            new_name='FC_clearanc_academi_805d74_idx',
            old_name='FC_clearanc_academi_4d3f82_idx',
        ),
        migrations.RenameIndex(
            model_name='clearancetimeline',
            new_name='FC_clearanc_term_b68d08_idx',
            old_name='FC_clearanc_term_9f7df6_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('approved_clearance', 'approved_clearance'), ('rejected_clearance', 'rejected_clearance'), ('create_request', 'create_request'), ('created_requirements', 'created_requirements'), ('edited_requirements', 'edited_requirements'), ('deleted_requirements', 'deleted_requirements'), ('edited_announcement', 'edited_announcement'), ('user_login', 'user_login'), ('user_logout', 'user_logout'), ('added_assistant_approver', 'added_assistant_approver'), ('updated_assistant_approver', 'updated_assistant_approver'), ('removed_assistant_approver', 'removed_assistant_approver'), ('created_guideline', 'created_guideline'), ('edited_guideline', 'edited_guideline'), ('enabled_guideline', 'enabled_guideline'), ('disabled_guideline', 'disabled_guideline'), ('delete_guideline', 'delete_guideline'), ('archived_guideline', 'archived_guideline'), ('created_announcement', 'created_announcement'), ('enabled_announcement', 'enabled_announcement'), ('disabled_announcement', 'disabled_announcement'), ('deleted_announcement', 'deleted_announcement'), ('active_timeline', 'active_timeline'), ('inactive_timeline', 'inactive_timeline'), ('created_college', 'created_college'), ('edited_college', 'edited_college'), ('deleted_college', 'deleted_college'), ('created_department', 'created_department'), ('edited_department', 'edited_department'), ('deleted_department', 'deleted_department'), ('created_office', 'created_office'), ('edited_office', 'edited_office'), ('deleted_office', 'deleted_office')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='FC.college'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='FC.department'),
        ),
    ]
