# Generated by Django 5.1.4 on 2026-03-26 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0011_merge_20260323_1750'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clearance',
            new_name='FC_clearanc_academi_e5d704_idx',
            old_name='FC_clearanc_academi_7f9c77_idx',
        ),
        migrations.RenameIndex(
            model_name='clearance',
            new_name='FC_clearanc_faculty_28eaba_idx',
            old_name='FC_clearanc_faculty_f42c13_idx',
        ),
        migrations.RenameIndex(
            model_name='clearancerequest',
            new_name='FC_clearanc_clearan_a77ae5_idx',
            old_name='FC_clearanc_clearan_7dff0a_idx',
        ),
        migrations.RenameIndex(
            model_name='clearancerequest',
            new_name='FC_clearanc_status_2c2a92_idx',
            old_name='FC_clearanc_status_5c4b44_idx',
        ),
        migrations.RenameIndex(
            model_name='clearancetimeline',
            new_name='FC_clearanc_is_acti_9a9351_idx',
            old_name='FC_clearanc_is_acti_ae2d65_idx',
        ),
        migrations.RenameIndex(
            model_name='clearancetimeline',
            new_name='FC_clearanc_academi_805d74_idx',
            old_name='FC_clearanc_academi_4d3f82_idx',
        ),
        migrations.RenameIndex(
            model_name='clearancetimeline',
            new_name='FC_clearanc_term_b68d08_idx',
            old_name='FC_clearanc_term_9f7df6_idx',
        ),
        migrations.AddField(
            model_name='requirement',
            name='approver_flow_step',
            field=models.ForeignKey(blank=True, help_text='Select which approver flow step this requirement belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='FC.approverflowstep'),
        ),
    ]
